
drop table if exists category CASCADE ;

drop table if exists product CASCADE ;

create table category (
    category_id bigint generated by default as identity,
    category_name varchar(255),
    primary key (category_id)
    );


create table product (
    product_id bigint generated by default as identity,
    active boolean,
    date_created timestamp,
    description varchar(255),
    last_updated timestamp,
    name varchar(255),
    unit_price decimal(19,2),
    category_id bigint not null,
    primary key (product_id)
   );

alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category
